//
//  BeerDetailModels.swift
//  TheBeerProject_CA
//
//  Created by Nunzio Giulio Caggegi on 02/02/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum BeerDetail
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
        var beer: Beer?
        
        init(beer: Beer?) {
            self.beer = beer
        }
    }
    struct ViewModel
    {
        var beer: Beer?
        
        init(beer: Beer?) {
            self.beer = beer
        }
    }
  }
}
