//
//  BeerDetailPresenter.swift
//  TheBeerProject_CA
//
//  Created by Nunzio Giulio Caggegi on 02/02/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BeerDetailPresentationLogic
{
  func presentBeerDetail(response: BeerDetail.Something.Response)
}

class BeerDetailPresenter: BeerDetailPresentationLogic
{
  weak var viewController: BeerDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentBeerDetail(response: BeerDetail.Something.Response)
  {
    let viewModel = BeerDetail.Something.ViewModel(beer: response.beer)
    viewController?.displaySomething(viewModel: viewModel)
  }
}
