//
//  BeerDetailInteractor.swift
//  TheBeerProject_CA
//
//  Created by Nunzio Giulio Caggegi on 02/02/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BeerDetailBusinessLogic
{
  func fetchBeerDetail()
}

protocol BeerDetailDataStore
{
    var beer: Beer? { get set }
}

class BeerDetailInteractor: BeerDetailBusinessLogic, BeerDetailDataStore
{
    var beer: Beer? = nil
        
  var presenter: BeerDetailPresentationLogic?
  var worker: BeerDetailWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func fetchBeerDetail() {
    
    let response = BeerDetail.Something.Response(beer: beer)
    presenter?.presentBeerDetail(response: response)
  }
}
