//
//  HomeListBeersPresenter.swift
//  TheBeerProject_CA
//
//  Created by Nunzio Giulio Caggegi on 01/02/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeListBeersPresentationLogic
{
    func presentBeersResponse(response: HomeListBeers.Something.Response)
    func presentCategories(response: HomeListBeers.Categories.Response)
}

class HomeListBeersPresenter: HomeListBeersPresentationLogic
{
  weak var viewController: HomeListBeersDisplayLogic?
  
  // MARK: Do something
  
  func presentBeersResponse(response: HomeListBeers.Something.Response)
  {
    let viewModel = HomeListBeers.Something.ViewModel(beers: response.beers)
    viewController?.displayBeersList(viewModel: viewModel)
  }
    
    func presentCategories(response: HomeListBeers.Categories.Response) {
        let viewModel = HomeListBeers.Categories.ViewModel(categories: response.categories)
        viewController?.displayCategories(viewModel: viewModel)
    }
}
