//
//  HomeListBeersRouter.swift
//  TheBeerProject_CA
//
//  Created by Nunzio Giulio Caggegi on 01/02/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeListBeersRoutingLogic
{
  func routeToDetail()
}

protocol HomeListBeersDataPassing
{
  var dataStore: HomeListBeersDataStore? { get }
}

class HomeListBeersRouter: NSObject, HomeListBeersRoutingLogic, HomeListBeersDataPassing
{
  weak var viewController: HomeListBeersViewController?
  var dataStore: HomeListBeersDataStore?
  
  // MARK: Routing
  
  func routeToDetail() {
    let destination = BeerDetailViewController()
    var destinationDS = destination.router?.dataStore
    passDataToSomewhere(source: self.dataStore!, destination: &destinationDS!)
    navigateToDetail(source: self.viewController!, destination: destination)
  }

  // MARK: Navigation
  
  func navigateToSomewhere(source: HomeListBeersViewController, destination: BeerDetailViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToSomewhere(source: HomeListBeersDataStore, destination: inout BeerDetailDataStore) {
    destination.beer = source.beerToDetail
  }
}

extension HomeListBeersRouter {
    func navigateToDetail(source: HomeListBeersViewController, destination: BeerDetailViewController) {
        DispatchQueue.main.async {
            destination.modalPresentationStyle = .overFullScreen
            source.present(destination, animated: true, completion: nil)
        }
    }
}
