//
//  HomeListBeersWorker.swift
//  TheBeerProject_CA
//
//  Created by Nunzio Giulio Caggegi on 01/02/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Falcon

class HomeListBeersWorker {
    func callAPIBeers(page: Int, beerName: String = "", category: String = "", completion: ((Beers?) -> ())?) {
        
        self.getBeers(page: page, beerName: beerName, category: category) { (response) in
        if let data = response?.data {
            let decoder = JSONDecoder()
            if let beersDecoded = try? decoder.decode(Beers.self, from: data) {
                completion?(beersDecoded)
            } else {
                completion?(nil)
            }
        }
    }
  }
    
    private func getBeers(page: Int, beerName: String, category: String, completion: @escaping (FalconResponse?) -> ()) {
        var uri = "beers?page=\(page)&per_page=25"
        if category != "" && category != "All" {
            uri.append("&malt=\(category)")
        }
        if beerName != "" {
             uri.append("&beer_name=\(beerName)")
             Falcon.request(url: uri, method: .get) { (result) in
                switch result {
                case let .success(response):
                    completion(response)
                case let .error(response, _):
                    completion(response)
                }
            }
        } else {
            Falcon.request(url: uri, method: .get) { (result) in
               switch result {
               case let .success(response):
                   completion(response)
               case let .error(response, _):
                   completion(response)
               }
           }
        }
    }
    
    func fetchCategories(completion: @escaping ([String]) -> ()) {
        completion(["All", "Pilsner", "Lager", "Ale", "Amber", "Dark", "Brown", "Cream", "Red", "Golden", "Fruit", "Honey"])
    }
}
