//
//  HomeListBeersModels.swift
//  TheBeerProject_CA
//
//  Created by Nunzio Giulio Caggegi on 01/02/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum HomeListBeers
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
        var page: Int? = 1
        
        var beerName: String? = ""
        
        var category: Category? = Category(category: "", shouldSelect: false)
    }
    struct Response
    {
        var beers: [Beer]?
    }
    struct ViewModel
    {
        var beers: [Beer]?
    }
  }
    
    enum Categories
    {
      struct Request
      {
        var index: Int
        var category: Category
      }
        
        struct NormalRequest {
            
        }
      struct Response
      {
          var categories: [Category]
      }
      struct ViewModel
      {
        var categories: [Category]
      }
    }
}
